[package]
name = "os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# 引入RustSBI 实现输出和关机
[dependencies]
sbi-rt = {version = "0.0.2", features = ["legacy"]}
